export const HOME_URL = "http://thekingsaga.com:15457/api/"
export const IMAGE_URL = "http://thekingsaga.com/backend/"
//export const HOME_URL = "https://thekingsaga.com"
export const API_URL2 = "http://thekingsaga.com:15457/api/"
export const GET_HEADER_MENU_LIST = "/getHeaderMenuList"
export const GET_AUTH_INFO = "/authTokenInfo"
//LOGIN
export const USER_LOGIN = "/login"
export const POST_PASSWORD_FORGET = "/forgotPassword"
export const CHECK_EMAIL_AVLBE = "/checkEmailAvailable"
export const CHECK_MOB_AVLBE = "/checkMobileAvailable"
export const POST_RESET_PASSWORD = "/resetPassword"
export const USER_SIGNUP = "/signup"
export const MOBILE_VERIFIED = "/phoneVerified"
export const EMAIL_VEREIFIED = "/emailVerified"

//admin
export const ADMIN_REQUESTED_LISTS="/admin/salonRequestedList"
export const UPDATE_NOTES_STATUS="admin/updateNotesAndStatus"
//admin


//salon
export const MEMBERSHIPS_LISTS="/salon/membershipList"
export const PURCHASE_MEMBERSHIP="/salon/purchaseMembership"
export const GET_ABOUT_COMPANY="/salon/getAboutCompany"
export const UPDATE_ABOUT_COMPANY="/salon/updateAboutCompany"
export const UPDATE_WORKING_HOURS="/salon/updateWorkingHours"
export const SALON_SERVICES_LIST="/salon/salonServiceList"
export const GET_WORKING_HOURS="/salon/getWorkingHours"
export const GET_WORK_PORTFOLIO="/salon/getWorkPortfolio"
export const GET_SERVICE_DROPDOWN="/salon/salonServiceDropDown"
export const GET_SALON_RESOURCES="/salon/getSalonResources"
export const GET_SALON_AMENITIES="/salon/getSalonAminity"
export const ADD_WORK_PORTFOLIO="/salon/addWorkPortfolio"
export const GET_MEMBERSHIP_LISTS="/salon/membershipNameList"
export const ADD_SALON_SERVICES="/salon/addSalonServicePrice"
export const ADD_SALON_RESOURCES="/salon/addSalonResources"
export const GET_SALON_SERVICE_LIST="/salon/salonServiceGroupList"
export const GET_SALON_SERVICE_LIST_BYID="/salon/salonServiceListById"
export const ADD_MULTIPLE_SALON_SERVICE="/salon/addMultipleSalonServicePrice"
export const GET_SALON_LANG="/salon/getSalonLanguage"
export const UPDATE_SALON_LANG="/salon/updateSalonLanguage"
export const UPDATE_SALON_AMINITY="/salon/updateSalonAminity"
export const MEMBERSHIP_PLANS_NAMES="/salon/membershipList"
export const MEMBERSHIP_ADDON_LIST="salon/membershipAddonList"
export const ACTIVATED_MEMBERSHIP="salon/activeMembership"
export const GET_SALON_INVOICE="salon/getSalonInvocing"
export const MEMBERSHIP_AUTO_RENEW="salon/membershipAutoRenew"
export const GET_EMPLOYEE_LIST="salon/getEmployeeList?pagesize=1000&page=1"
export const EMPLOYEE_REGISTRATION="salon/employeeRegistration"
export const UPDATE_TEAM_DETAIL="salon/updateTeamMemberDetail"
export const GET_TEAM_MEMBER_SERVICE="salon/getTeamMemberService"
export const GET_EMPLOYEE_INFO="salon/getEmployeeInfo"
export const ADD_TEAM_MEMBER_SERVICE="salon/addTeamMemberService"
export const GET_TEAM_MEMBER_PORTFOLIO="salon/getTeamMemberPortfolio"
export const RESEND_OTP="resendOtpRequest"



//salon