export const LOGIN_USER = "LOGIN_USER"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"

export const EMAIL_VEREIFICATION = "EMAIL_VEREIFICATION"
export const EMAIL_VEREIFICATION_SUCCESS = "EMAIL_VEREIFICATION_SUCCESS"
export const EMAIL_VEREIFICATION_FAILURE = "EMAIL_VEREIFICATION_FAILURE"
export const MOBILE_VERIFICATION_SUCCESS = "MOBILE_VERIFICATION_SUCCESS"
export const API_ERROR = "LOGIN_API_ERROR"

